export const LIST_CATEGORIES = 'LIST_CATEGORIES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY_PROD = 'FETCH_CATEGORY_PROD';
export const FETCH_PROD_DETAIL = 'FETCH_PROD_DETAIL';
export const FETCH_PROD = 'FETCH_PROD';
export const FETCH_PROD_REVIEW = 'FETCH_PROD_REVIEW';