/** @format */

// ecomShop;
export const ecomShop = {
	FETCH_DEPARTMENTS: 'FETCH_DEPARTMENTS',
	LIST_CATEGORIES: 'LIST_CATEGORIES',
	FETCH_CATEGORIES: 'FETCH_CATEGORIES',
	FETCH_CATEGORY_PROD: 'FETCH_CATEGORY_PROD',
	FETCH_PROD_DETAIL: 'FETCH_PROD_DETAIL',
	FETCH_PROD: 'FETCH_PROD',
	FETCH_PROD_REVIEW: 'FETCH_PROD_REVIEW',
	FETCH_SIZE_ATTRIBUTE: 'FETCH_SIZE_ATTRIBUTE',
	FETCH_COLOR_ATTRIBUTE: 'FETCH_COLOR_ATTRIBUTE',
	SEARCH_QUERY: 'SEARCH_QUERY',
	ADD_TO_CART: 'ADD_TO_CART',
	ADD_TO_SHOP: 'ADD_TO_SHOP',
};
